# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20170419_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='did',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='did',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='rid',
            new_name='id',
        ),
    ]
