# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='id',
            new_name='did',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='id',
            new_name='did',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='id',
            new_name='rid',
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='hospital.Doctor'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='hospital.Patient'),
        ),
    ]
